# CI専用Ruff設定
#
# 通常の開発環境では pyproject.toml を使用する。
# CIでは、このファイルを通して低優先度のルールを緩和する。

extend = "../../pyproject.toml"


[lint]
ignore = [
    "I001",
    "D205",
    "D403",
    "D202",
    "D100",
    "PTH",
    "UP015",
    "UP017",
    "B905",
]