errorConfig:
    errorMode: percent # 'abusolute' or 'percent'
    errorSizes: # 半径補正は偏差値動画にないので再現もなし
        - 3 # centerX
        - 3 # centerY

sampleConfig:
    cropHW:
        - 600 # h
        - 600 # w
    imagePath: "" #1channel画像のみ対応
min2Config: #ver2.2.1
    n: 10
    light_threshold: 50
    limb_wigth: 24
    show: false
    debug: false
